export const FETCH_LATEST_PRODUCTS_REQUEST =
  "reducer.product.FETCH_LATEST_PRODUCTS_REQUEST";
export const FETCH_LATEST_PRODUCTS_SUCCESS =
  "reducer.product.FETCH_LATEST_PRODUCTS_SUCCESS";
export const FETCH_LATEST_PRODUCTS_FALIURE =
  "reducer.product.FETCH_LATEST_PRODUCTS_FALIURE";
